# Generated by Django 3.0.4 on 2022-03-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infocategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
